### PR TITLE
In .replace(), optionally avoid selecting the text after the replacement

### LINKED ISSUE #14: Add textFieldEdit.replace option that doesn't change selection
In some situations, you want to programmatically edit text in a textbox without generating a selection.  (E.g. one use case I have for this is inserting a placeholder into the textarea while we wait to fetch data from the server, and then replacing the placeholder with the value returned from the server).  I'd want to use `textFieldEdit.replace` for this, but it also selects content, which we don't want.

```
textFieldEdit.replace(field, searchValue, replacement)
Finds and replaces strings and regular expressions in the field’s value, like field.value = field.value.replace() but leaves the last replacement selected like a text editor would.
```

It'd be nice if there were either a variant to do this or a way to pass an additional option to disable the selection part of the function.

### PR DESCRIPTION
**Pull request by amanagr**
I am not sure if it fixed #14, but it does resolve our use case.

### CODE REVIEW

**Comment by fregante** [comment]
Thank you for the PR! I think the expectation in a test is incorrect, or it's missing the new config

**Comment by amanagr** [comment]
image

It is failing for Firefox due to dependencies being outdated:
image

**Comment by amanagr** [comment]
@fregante thanks for updating the dependencies! Let me know if you need me to do anything else.

**Comment by amanagr** [comment]
@fregante it would be great if you can do a release for this!

**Comment by fregante** [comment]
heh I was just about to 😃

**Pull request merged**
